from typing import Dict, Any

MCC_DATA: Dict[str, Dict[str, str]] = {
    "0742": {"category": "Veterinary Services", "group": "Professional Services", "restricted": "No"},
    "0763": {"category": "Agricultural Cooperatives", "group": "Agriculture", "restricted": "No"},
    "1520": {"category": "General Contractors - Residential", "group": "Construction", "restricted": "No"},
    "1711": {"category": "Heating, Plumbing, AC Contractors", "group": "Construction", "restricted": "No"},
    "2741": {"category": "Miscellaneous Publishing", "group": "Media", "restricted": "No"},
    "3000": {"category": "United Airlines", "group": "Airlines", "restricted": "No"},
    "3001": {"category": "American Airlines", "group": "Airlines", "restricted": "No"},
    "3007": {"category": "Southwest Airlines", "group": "Airlines", "restricted": "No"},
    "3008": {"category": "Delta Air Lines", "group": "Airlines", "restricted": "No"},
    "4011": {"category": "Railroads", "group": "Transportation", "restricted": "No"},
    "4111": {"category": "Local/Suburban Commuter Transport", "group": "Transportation", "restricted": "No"},
    "4121": {"category": "Taxicabs and Rideshares", "group": "Transportation", "restricted": "No"},
    "4215": {"category": "Courier Services", "group": "Shipping", "restricted": "No"},
    "4511": {"category": "Airlines and Air Carriers", "group": "Airlines", "restricted": "No"},
    "4722": {"category": "Travel Agencies", "group": "Travel", "restricted": "No"},
    "4816": {"category": "Computer Network Services", "group": "Technology", "restricted": "No"},
    "4899": {"category": "Cable and Streaming Services", "group": "Utilities", "restricted": "No"},
    "5045": {"category": "Computers and Peripherals", "group": "Electronics", "restricted": "No"},
    "5065": {"category": "Electronic Parts and Equipment", "group": "Electronics", "restricted": "No"},
    "5072": {"category": "Hardware Equipment and Supplies", "group": "Retail", "restricted": "No"},
    "5094": {"category": "Precious Stones and Metals", "group": "Retail", "restricted": "No"},
    "5111": {"category": "Stationery and Office Supplies", "group": "Retail", "restricted": "No"},
    "5137": {"category": "Uniforms and Commercial Clothing", "group": "Retail", "restricted": "No"},
    "5192": {"category": "Books and Publications", "group": "Retail", "restricted": "No"},
    "5200": {"category": "Home Supply Warehouse Stores", "group": "Retail", "restricted": "No"},
    "5251": {"category": "Hardware Stores", "group": "Retail", "restricted": "No"},
    "5300": {"category": "Wholesale Clubs", "group": "Retail", "restricted": "No"},
    "5309": {"category": "Duty Free Stores", "group": "Retail", "restricted": "No"},
    "5310": {"category": "Discount Stores", "group": "Retail", "restricted": "No"},
    "5311": {"category": "Department Stores", "group": "Retail", "restricted": "No"},
    "5331": {"category": "Variety Stores", "group": "Retail", "restricted": "No"},
    "5399": {"category": "General Merchandise", "group": "Retail", "restricted": "No"},
    "5411": {"category": "Grocery Stores and Supermarkets", "group": "Grocery", "restricted": "No"},
    "5422": {"category": "Meat Provisioners and Freezer", "group": "Grocery", "restricted": "No"},
    "5441": {"category": "Candy and Confectionery Stores", "group": "Grocery", "restricted": "No"},
    "5451": {"category": "Dairy Products Stores", "group": "Grocery", "restricted": "No"},
    "5462": {"category": "Bakeries", "group": "Grocery", "restricted": "No"},
    "5499": {"category": "Misc Food Stores", "group": "Grocery", "restricted": "No"},
    "5511": {"category": "Car and Truck Dealers (New/Used)", "group": "Automotive", "restricted": "No"},
    "5521": {"category": "Car and Truck Dealers (Used Only)", "group": "Automotive", "restricted": "No"},
    "5531": {"category": "Auto and Home Supply Stores", "group": "Automotive", "restricted": "No"},
    "5532": {"category": "Automotive Tire Stores", "group": "Automotive", "restricted": "No"},
    "5533": {"category": "Automotive Parts and Accessories", "group": "Automotive", "restricted": "No"},
    "5541": {"category": "Service Stations (Gas)", "group": "Automotive", "restricted": "No"},
    "5542": {"category": "Automated Fuel Dispensers", "group": "Automotive", "restricted": "No"},
    "5571": {"category": "Motorcycle Shops and Dealers", "group": "Automotive", "restricted": "No"},
    "5611": {"category": "Mens Clothing Stores", "group": "Apparel", "restricted": "No"},
    "5621": {"category": "Womens Clothing Stores", "group": "Apparel", "restricted": "No"},
    "5631": {"category": "Womens Accessory Stores", "group": "Apparel", "restricted": "No"},
    "5641": {"category": "Childrens Clothing Stores", "group": "Apparel", "restricted": "No"},
    "5651": {"category": "Family Clothing Stores", "group": "Apparel", "restricted": "No"},
    "5661": {"category": "Shoe Stores", "group": "Apparel", "restricted": "No"},
    "5691": {"category": "Mens and Womens Clothing", "group": "Apparel", "restricted": "No"},
    "5699": {"category": "Misc Apparel and Accessories", "group": "Apparel", "restricted": "No"},
    "5712": {"category": "Furniture and Home Furnishings", "group": "Home", "restricted": "No"},
    "5722": {"category": "Household Appliance Stores", "group": "Home", "restricted": "No"},
    "5732": {"category": "Electronics Stores", "group": "Electronics", "restricted": "No"},
    "5733": {"category": "Music Stores and Instruments", "group": "Retail", "restricted": "No"},
    "5734": {"category": "Computer Software Stores", "group": "Technology", "restricted": "No"},
    "5735": {"category": "Record Stores", "group": "Retail", "restricted": "No"},
    "5812": {"category": "Eating Places and Restaurants", "group": "Food & Beverage", "restricted": "No"},
    "5813": {"category": "Bars and Drinking Places", "group": "Food & Beverage", "restricted": "No"},
    "5814": {"category": "Fast Food Restaurants", "group": "Food & Beverage", "restricted": "No"},
    "5912": {"category": "Drug Stores and Pharmacies", "group": "Health", "restricted": "No"},
    "5921": {"category": "Package Stores - Beer, Wine, Liquor", "group": "Retail", "restricted": "Yes"},
    "5931": {"category": "Used Merchandise Stores", "group": "Retail", "restricted": "No"},
    "5932": {"category": "Antique Shops", "group": "Retail", "restricted": "No"},
    "5933": {"category": "Pawn Shops", "group": "Financial Services", "restricted": "Yes"},
    "5935": {"category": "Wrecking and Salvage Yards", "group": "Automotive", "restricted": "No"},
    "5941": {"category": "Sporting Goods Stores", "group": "Retail", "restricted": "No"},
    "5942": {"category": "Book Stores", "group": "Retail", "restricted": "No"},
    "5943": {"category": "Stationery Stores", "group": "Retail", "restricted": "No"},
    "5944": {"category": "Jewelry Stores", "group": "Retail", "restricted": "No"},
    "5945": {"category": "Hobby, Toy, and Game Shops", "group": "Retail", "restricted": "No"},
    "5946": {"category": "Camera and Photographic Supply", "group": "Retail", "restricted": "No"},
    "5947": {"category": "Gift, Card, Novelty Stores", "group": "Retail", "restricted": "No"},
    "5948": {"category": "Luggage and Leather Goods", "group": "Retail", "restricted": "No"},
    "5960": {"category": "Direct Marketing - Insurance", "group": "Insurance", "restricted": "No"},
    "5962": {"category": "Direct Marketing - Travel", "group": "Travel", "restricted": "No"},
    "5964": {"category": "Direct Marketing - Catalog", "group": "Retail", "restricted": "No"},
    "5965": {"category": "Direct Marketing - Combo Catalog/Retail", "group": "Retail", "restricted": "No"},
    "5966": {"category": "Direct Marketing - Outbound Telemarketing", "group": "Marketing", "restricted": "Yes"},
    "5967": {"category": "Direct Marketing - Inbound Teleservices", "group": "Marketing", "restricted": "No"},
    "5968": {"category": "Direct Marketing - Subscription", "group": "Media", "restricted": "No"},
    "5969": {"category": "Direct Marketing - Other", "group": "Marketing", "restricted": "No"},
    "5970": {"category": "Artists Supply Stores", "group": "Retail", "restricted": "No"},
    "5971": {"category": "Art Dealers and Galleries", "group": "Retail", "restricted": "No"},
    "5972": {"category": "Stamp and Coin Stores", "group": "Retail", "restricted": "No"},
    "5973": {"category": "Religious Goods Stores", "group": "Retail", "restricted": "No"},
    "5976": {"category": "Orthopedic Goods", "group": "Health", "restricted": "No"},
    "5977": {"category": "Cosmetic Stores", "group": "Retail", "restricted": "No"},
    "5978": {"category": "Typewriter Stores", "group": "Retail", "restricted": "No"},
    "5983": {"category": "Fuel Dealers", "group": "Utilities", "restricted": "No"},
    "5992": {"category": "Florists", "group": "Retail", "restricted": "No"},
    "5993": {"category": "Cigar Stores and Stands", "group": "Retail", "restricted": "Yes"},
    "5994": {"category": "News Dealers", "group": "Retail", "restricted": "No"},
    "5995": {"category": "Pet Shops and Pet Food", "group": "Retail", "restricted": "No"},
    "5999": {"category": "Miscellaneous Retail Stores", "group": "Retail", "restricted": "No"},
    "6010": {"category": "Financial Institutions - Manual Cash", "group": "Financial Services", "restricted": "No"},
    "6011": {"category": "Financial Institutions - ATM", "group": "Financial Services", "restricted": "No"},
    "6012": {"category": "Financial Institutions - Merchandise", "group": "Financial Services", "restricted": "No"},
    "6051": {"category": "Non-Financial Institutions - Foreign Currency/Money Orders", "group": "Financial Services", "restricted": "Yes"},
    "6211": {"category": "Security Brokers/Dealers", "group": "Financial Services", "restricted": "No"},
    "6300": {"category": "Insurance Underwriting", "group": "Insurance", "restricted": "No"},
    "6513": {"category": "Real Estate Agents - Rentals", "group": "Real Estate", "restricted": "No"},
    "6540": {"category": "Non-Financial Institutions - Stored Value Card", "group": "Financial Services", "restricted": "Yes"},
    "7011": {"category": "Hotels and Motels", "group": "Lodging", "restricted": "No"},
    "7032": {"category": "Sporting and Recreational Camps", "group": "Recreation", "restricted": "No"},
    "7210": {"category": "Laundry and Cleaning Services", "group": "Services", "restricted": "No"},
    "7211": {"category": "Laundry Services - Family/Commercial", "group": "Services", "restricted": "No"},
    "7216": {"category": "Dry Cleaners", "group": "Services", "restricted": "No"},
    "7230": {"category": "Beauty and Barber Shops", "group": "Services", "restricted": "No"},
    "7251": {"category": "Shoe Repair and Hat Cleaning", "group": "Services", "restricted": "No"},
    "7261": {"category": "Funeral Services and Crematories", "group": "Services", "restricted": "No"},
    "7273": {"category": "Dating and Escort Services", "group": "Services", "restricted": "Yes"},
    "7276": {"category": "Tax Preparation Services", "group": "Professional Services", "restricted": "No"},
    "7277": {"category": "Counseling Services", "group": "Professional Services", "restricted": "No"},
    "7278": {"category": "Buying and Shopping Services", "group": "Services", "restricted": "No"},
    "7296": {"category": "Clothing Rental", "group": "Services", "restricted": "No"},
    "7297": {"category": "Massage Parlors", "group": "Services", "restricted": "Yes"},
    "7298": {"category": "Health and Beauty Spas", "group": "Services", "restricted": "No"},
    "7299": {"category": "Miscellaneous Recreation Services", "group": "Services", "restricted": "No"},
    "7311": {"category": "Advertising Services", "group": "Professional Services", "restricted": "No"},
    "7321": {"category": "Consumer Credit Reporting Agencies", "group": "Financial Services", "restricted": "No"},
    "7333": {"category": "Commercial Photography and Graphic Design", "group": "Professional Services", "restricted": "No"},
    "7338": {"category": "Quick Copy and Reproduction", "group": "Services", "restricted": "No"},
    "7339": {"category": "Stenographic and Secretarial Support", "group": "Services", "restricted": "No"},
    "7342": {"category": "Exterminating and Disinfecting", "group": "Services", "restricted": "No"},
    "7349": {"category": "Cleaning and Maintenance", "group": "Services", "restricted": "No"},
    "7361": {"category": "Employment Agencies and Temp Staffing", "group": "Services", "restricted": "No"},
    "7372": {"category": "Computer Programming and Data Processing", "group": "Technology", "restricted": "No"},
    "7375": {"category": "Information Retrieval Services", "group": "Technology", "restricted": "No"},
    "7379": {"category": "Computer Maintenance and Repair", "group": "Technology", "restricted": "No"},
    "7392": {"category": "Management Consulting Services", "group": "Professional Services", "restricted": "No"},
    "7393": {"category": "Detective and Protective Agencies", "group": "Services", "restricted": "No"},
    "7394": {"category": "Equipment Rental and Leasing", "group": "Services", "restricted": "No"},
    "7395": {"category": "Photofinishing Laboratories", "group": "Services", "restricted": "No"},
    "7399": {"category": "Miscellaneous Business Services", "group": "Services", "restricted": "No"},
    "7512": {"category": "Car Rental Agencies", "group": "Transportation", "restricted": "No"},
    "7513": {"category": "Truck and Utility Trailer Rental", "group": "Transportation", "restricted": "No"},
    "7519": {"category": "Motor Home and Recreational Vehicle Rental", "group": "Transportation", "restricted": "No"},
    "7523": {"category": "Parking Lots and Garages", "group": "Transportation", "restricted": "No"},
    "7531": {"category": "Automotive Body Repair Shops", "group": "Automotive", "restricted": "No"},
    "7534": {"category": "Tire Retreading and Repair", "group": "Automotive", "restricted": "No"},
    "7535": {"category": "Automotive Paint Shops", "group": "Automotive", "restricted": "No"},
    "7538": {"category": "Automotive Service Shops", "group": "Automotive", "restricted": "No"},
    "7542": {"category": "Car Washes", "group": "Automotive", "restricted": "No"},
    "7549": {"category": "Towing Services", "group": "Automotive", "restricted": "No"},
    "7622": {"category": "Electronics Repair Shops", "group": "Services", "restricted": "No"},
    "7623": {"category": "AC and Refrigeration Repair", "group": "Services", "restricted": "No"},
    "7629": {"category": "Small Appliance Repair Shops", "group": "Services", "restricted": "No"},
    "7631": {"category": "Watch and Jewelry Repair", "group": "Services", "restricted": "No"},
    "7641": {"category": "Furniture Reupholstery and Repair", "group": "Services", "restricted": "No"},
    "7692": {"category": "Welding Repair", "group": "Services", "restricted": "No"},
    "7699": {"category": "Miscellaneous Repair Shops", "group": "Services", "restricted": "No"},
    "7800": {"category": "Government-Owned Lotteries", "group": "Gambling", "restricted": "Yes"},
    "7801": {"category": "Government-Licensed Online Casinos", "group": "Gambling", "restricted": "Yes"},
    "7802": {"category": "Government-Licensed Horse/Dog Racing", "group": "Gambling", "restricted": "Yes"},
    "7829": {"category": "Motion Picture Distribution", "group": "Entertainment", "restricted": "No"},
    "7832": {"category": "Motion Picture Theaters", "group": "Entertainment", "restricted": "No"},
    "7841": {"category": "Video Tape Rental Stores", "group": "Entertainment", "restricted": "No"},
    "7911": {"category": "Dance Halls and Studios", "group": "Entertainment", "restricted": "No"},
    "7922": {"category": "Theatrical Producers", "group": "Entertainment", "restricted": "No"},
    "7929": {"category": "Bands and Orchestras", "group": "Entertainment", "restricted": "No"},
    "7932": {"category": "Billiard and Pool Establishments", "group": "Entertainment", "restricted": "No"},
    "7933": {"category": "Bowling Alleys", "group": "Entertainment", "restricted": "No"},
    "7941": {"category": "Commercial Sports and Athletic Fields", "group": "Entertainment", "restricted": "No"},
    "7991": {"category": "Tourist Attractions and Exhibits", "group": "Entertainment", "restricted": "No"},
    "7992": {"category": "Public Golf Courses", "group": "Entertainment", "restricted": "No"},
    "7993": {"category": "Video Amusement Game Supplies", "group": "Entertainment", "restricted": "No"},
    "7994": {"category": "Video Game Arcades", "group": "Entertainment", "restricted": "No"},
    "7995": {"category": "Betting and Casino Gambling", "group": "Gambling", "restricted": "Yes"},
    "7996": {"category": "Amusement Parks and Carnivals", "group": "Entertainment", "restricted": "No"},
    "7997": {"category": "Membership Clubs and Country Clubs", "group": "Recreation", "restricted": "No"},
    "7998": {"category": "Aquariums and Zoos", "group": "Entertainment", "restricted": "No"},
    "7999": {"category": "Recreation Services", "group": "Recreation", "restricted": "No"},
    "8011": {"category": "Doctors - Not Elsewhere Classified", "group": "Healthcare", "restricted": "No"},
    "8021": {"category": "Dentists and Orthodontists", "group": "Healthcare", "restricted": "No"},
    "8031": {"category": "Osteopaths", "group": "Healthcare", "restricted": "No"},
    "8041": {"category": "Chiropractors", "group": "Healthcare", "restricted": "No"},
    "8042": {"category": "Optometrists and Ophthalmologists", "group": "Healthcare", "restricted": "No"},
    "8043": {"category": "Opticians and Eyeglasses", "group": "Healthcare", "restricted": "No"},
    "8049": {"category": "Podiatrists and Chiropodists", "group": "Healthcare", "restricted": "No"},
    "8050": {"category": "Nursing and Personal Care Facilities", "group": "Healthcare", "restricted": "No"},
    "8062": {"category": "Hospitals", "group": "Healthcare", "restricted": "No"},
    "8071": {"category": "Medical and Dental Laboratories", "group": "Healthcare", "restricted": "No"},
    "8099": {"category": "Medical Services and Health Practitioners", "group": "Healthcare", "restricted": "No"},
    "8111": {"category": "Legal Services and Attorneys", "group": "Professional Services", "restricted": "No"},
    "8211": {"category": "Elementary and Secondary Schools", "group": "Education", "restricted": "No"},
    "8220": {"category": "Colleges and Universities", "group": "Education", "restricted": "No"},
    "8241": {"category": "Correspondence Schools", "group": "Education", "restricted": "No"},
    "8244": {"category": "Business and Secretarial Schools", "group": "Education", "restricted": "No"},
    "8249": {"category": "Vocational and Trade Schools", "group": "Education", "restricted": "No"},
    "8299": {"category": "Schools and Educational Services", "group": "Education", "restricted": "No"},
    "8351": {"category": "Child Care Services", "group": "Services", "restricted": "No"},
    "8398": {"category": "Charitable and Social Service Orgs", "group": "Nonprofit", "restricted": "No"},
    "8641": {"category": "Civic and Social Associations", "group": "Nonprofit", "restricted": "No"},
    "8651": {"category": "Political Organizations", "group": "Nonprofit", "restricted": "No"},
    "8661": {"category": "Religious Organizations", "group": "Nonprofit", "restricted": "No"},
    "8675": {"category": "Automobile Associations", "group": "Services", "restricted": "No"},
    "8699": {"category": "Membership Organizations", "group": "Nonprofit", "restricted": "No"},
    "8734": {"category": "Testing Laboratories", "group": "Professional Services", "restricted": "No"},
    "8911": {"category": "Architectural and Engineering Services", "group": "Professional Services", "restricted": "No"},
    "8931": {"category": "Accounting and Auditing Services", "group": "Professional Services", "restricted": "No"},
    "8999": {"category": "Professional Services - Not Elsewhere Classified", "group": "Professional Services", "restricted": "No"},
    "9211": {"category": "Court Costs and Fines", "group": "Government", "restricted": "No"},
    "9222": {"category": "Fines", "group": "Government", "restricted": "No"},
    "9223": {"category": "Bail and Bond Payments", "group": "Government", "restricted": "No"},
    "9311": {"category": "Tax Payments", "group": "Government", "restricted": "No"},
    "9399": {"category": "Government Services", "group": "Government", "restricted": "No"},
    "9402": {"category": "Postal Services - Government Only", "group": "Government", "restricted": "No"},
    "9405": {"category": "Intra-Government Purchases", "group": "Government", "restricted": "No"},
}

def get_mcc_details(mcc_code: str) -> Dict[str, Any]:
    clean_mcc = mcc_code.strip().zfill(4)[:4]

    if not clean_mcc.isdigit():
        return {"status": "error", "error": "MCC must be a 4-digit number", "mcc": mcc_code}

    if clean_mcc in MCC_DATA:
        data = MCC_DATA[clean_mcc]
        return {"status": "success", "mcc": clean_mcc, "category": data["category"], "group": data["group"], "restricted": data["restricted"]}

    return {"status": "not_found", "mcc": clean_mcc, "category": "Unknown", "group": "Unknown", "restricted": "Unknown"}
